### PR TITLE
[Shape] Add specific color for each shape

### PR DESCRIPTION
**Pull request by vbarthel-fr**
First step for having a notion of "difficulty" to identify shapes based on their colors. The idea is to have dedicated colors for each shape that would help the kid to identify the shape at the begining and then use a single color once she/he is familiar with the shapes.

### CODE REVIEW

**Comment by vbarthel-fr** [comment]
1496816908631_draw-diamond

The diamond has been rework so that its area is a little bit bigger.

**Comment by vbarthel-fr** [comment]
Tests will failed, Paint is part of the Android framework, the tests that use shapes should be moved into the connected test folders.

**Comment by vbarthel-fr** [comment]
Tests are now up-to-date =)

**Comment by tbarthel-fr** [comment]
LGTM 🌈

**Pull request merged**
