### PR TITLE
[Shape] Add the generation skeleton

### PR DESCRIPTION
**Pull request by vbarthel-fr**

### CODE REVIEW

**Review by jo-elimu — CHANGES_REQUESTED** [review]
Can we make sure that the simple shapes are taught first? Would it make sense to for example categorize triangles as simpler shapes then diamonds?

I'm suggesting listing the different types of shapes by frequency of occurrence in daily life, and systematically teach the most common ones first. Would this be possible?

**Comment by vbarthel-fr** [comment]
Sure, great idea, but it's kind of a little bit too early I guess. We are trying to build the basic components of the architecture first. After we have a solid base, it will be easy to tune the mechanisms and implement details =)

All those basic components are for us a way to build the core components - with a very simple version at first - so that we can easily split the work and have a better vision of the components and how the behave together.

We will keep you in the loop as soon as we have something we can use to iterate easily and adds such details!

I will open an issue to keep your comment in mind when we will dive into the game tuning. For now, we will focus on having a running minimum viable product =)

**Comment by vbarthel-fr** [comment]
I have opened a new issue for your suggestion: https://github.com/literacyapp-org/shapi/issues/8 =)

**Comment by tbarthel-fr** [comment]
LGTM 🐥

**Pull request merged**
